data_pipelines:
  name: NaverNews
  module: "module.data.providers.naver_news"
  base_path: "data/news"
  companies:
    - symbol: "005930"
      full_name: 삼성전자
      query: "삼성전자"
      display: 10
      exchange: KRX
      sector: "전자"

    - symbol: "073240"
      full_name: 금호타이어
      query: "금호타이어"
      display: 10
      exchange: KRX
      sector: "자동차"

    - symbol: "051900"
      full_name: LG생활건강
      query: "LG생활건강"
      display: 10
      exchange: KRX
      sector: "화학"

    - symbol: "034220"
      full_name: LG디스플레이
      query: "LG디스플레이"
      display: 10
      exchange: KRX
      sector: "전자"

    - symbol: "051910"
      full_name: LG화학
      query: "LG화학"
      display: 10
      exchange: KRX
      sector: "화학"

    - symbol: "267260"
      full_name: HD현대일렉트릭
      query: "HD현대일렉트릭"
      display: 10
      exchange: KRX
      sector: "전기"

    - symbol: "004370"
      full_name: 농심
      query: "농심"
      display: 10
      exchange: KRX
      sector: "식료품"

    - symbol: "005380"
      full_name: 현대자동차
      query: "현대자동차"
      display: 10
      exchange: KRX
      sector: "자동차"

