data_pipelines:
  name: YahooFinance
  module: "module.data.providers.yahoo_finance"
  base_path: "data/stocks/USA"
  interval: "1d"
  period: "max"
  start_date: "1970-01-01"
  end_date: "TODAY"
  stocks:
    - symbol: ^DJI
      full_name: DOW JONES INDUSTRIAL AVERAGE
      exchange: INDEXDJX
      sector: INDEX

    - symbol: ^IXIC
      full_name: NASDAQ COMPOSITE
      exchange: INDEXNASDAQ
      sector: INDEX

    - symbol: ^GSPC
      full_name: S&P 500
      exchange: INDEXSP
      sector: INDEX

    - symbol: ^VIX
      full_name: CBOE VOLATILITY INDEX
      exchange: CBOE
      sector: INDEX

    - symbol: ^TNX
      full_name: CBOE 10-YEAR TREASURY NOTE YIELD INDEX
      exchange: CBOE
      sector: INDEX

    - symbol: ^IRX
      full_name: CBOE 13-WEEK TREASURY BILL YIELD INDEX
      exchange: CBOE
      sector: INDEX

    - symbol: ^FVX
      full_name: CBOE 5-YEAR TREASURY NOTE YIELD INDEX
      exchange: CBOE
      sector: INDEX

    - symbol: ^TYX
      full_name: CBOE 30-YEAR TREASURY BOND YIELD INDEX
      exchange: CBOE
      sector: INDEX

    - symbol: ^RUT
      full_name: RUSSELL 2000 INDEX
      exchange: INDEXRUSSELL
      sector: INDEX

    - symbol: CL=F
      full_name: CRUDE OIL WTI
      exchange: NYMEX
      sector: COMMODITY

    - symbol: BZ=F
      full_name: CRUDE OIL BRENT
      exchange: NYMEX
      sector: COMMODITY

    - symbol: NG=F
      full_name: NATURAL GAS
      exchange: NYMEX
      sector: COMMODITY

    - symbol: GC=F
      full_name: GOLD
      exchange: COMEX
      sector: COMMODITY

    - symbol: SI=F
      full_name: SILVER
      exchange: COMEX
      sector: COMMODITY

    - symbol: HG=F
      full_name: COPPER
      exchange: COMEX
      sector: COMMODITY

    - symbol: ZC=F
      full_name: CORN
      exchange: CBOT
      sector: COMMODITY

    - symbol: ZW=F
      full_name: WHEAT
      exchange: CBOT
      sector: COMMODITY

    - symbol: ZS=F
      full_name: SOYBEAN
      exchange: CBOT
      sector: COMMODITY

    - symbol: KRW=X
      full_name: USD/KRW
      exchange: CCY
      sector: CURRENCY